#!/bin/bash
INPUT=$(cat)
FILE_PATH=$(echo "$INPUT" | jq -r '.tool_input.file_path // empty')

[ -z "$FILE_PATH" ] && exit 0

PROTECTED=(
  ".env"
  ".dev.vars"
  "pnpm-lock.yaml"
  "migrations/"
)

for pattern in "${PROTECTED[@]}"; do
  if [[ "$FILE_PATH" == *"$pattern"* ]]; then
    echo "Blocked: $FILE_PATH is protected. Migration files should be generated by drizzle-kit, not hand-edited." >&2
    exit 2
  fi
done

exit 0
