catalogMode: strict
packages:
  - apps/*
  - modules/*
  - packages/*

overrides:
  '@types/node': ^25.3.5

catalog:
  '@hono/zod-validator': ^0.7.6
  '@libsql/client': ^0.17.0
  better-auth: ^1.4.12
  drizzle-orm: ^0.45.1
  hono: ^4.12.5
  zod: ^4.3.6
