packages:
  - apps/*
  - modules/*
  - packages/*

catalog:
  '@hono/zod-validator': ^0.7.6
  '@hookform/resolvers': ^5.0.1
  '@libsql/client': ^0.17.0
  '@radix-ui/react-dialog': ^1.1.14
  '@radix-ui/react-dropdown-menu': ^2.1.15
  '@radix-ui/react-select': ^2.2.5
  '@radix-ui/react-tooltip': ^1.1.8
  '@tanstack/react-router': ^1.168.8
  '@tanstack/router-plugin': ^1.167.9
  '@types/react': ^19.2.7
  '@types/react-dom': ^19.2.3
  better-auth: ^1.4.12
  clsx: ^2.1.1
  concurrently: ^9.2.1
  drizzle-orm: ^0.45.1
  hono: ^4.12.5
  react: ^19.2.0
  react-dom: ^19.2.0
  react-hook-form: ^7.58.1
  tailwind-merge: ^3.3.0
  vite-plugin-svgr: ^5.0.0
  vitest: ^4.0.0
  zod: ^4.3.6

catalogMode: strict

overrides:
  '@types/node': ^25.3.5
